portfolio/polls/urls.py
from django.urls import path
from .views import *

app_name = "polls"
urlpatterns = [
    path("", programmers_list, name="index"),
    path("detail/<int:prog_id>", detail, name="detail"),
    path("add_user/", add_user, name="add_user"),
    path("user_save/", user_save, name="user_save"),
    path("add_project/<int:programmer_id>", add_project, name="add_project"),
    path("add_project_page/<int:programmer_id>", add_project_page, name="add_project_page"),
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("polls.urls")),
]

portfolio/polls/models.py
from django.db import models
from django.contrib.auth.models import User


class Programmer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=False)
    age = models.PositiveIntegerField(blank=False)
    language = models.CharField(max_length=50, blank=False)
    framework = models.CharField(max_length=50, blank=False)
    experience = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"


class Project(models.Model):
    programmer = models.ForeignKey(Programmer, on_delete=models.CASCADE, blank=False)
    name = models.CharField(max_length=100, blank=False)
    description = models.TextField(default="No description")

    def __str__(self):
        return self.name

portfolio/polls/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import Programmer, Project


# home page
def programmers_list(request):
    programmers = Programmer.objects.order_by("-age")
    contex = {"programmers": programmers}
    return render(request, "polls/index.html", contex)


# about users
def detail(request, prog_id):
    programmer = Programmer.objects.get(pk=prog_id)
    des = programmer.project_set.all()
    contex = {"programmer": programmer.user.first_name, "last_name": programmer.user.last_name,
              "age": programmer.age, "des": des, 'prog_id': programmer.id}
    return render(request, "polls/detail.html", contex)


# add User
def add_user(request):
    return render(request, "polls/add_user.html")


def user_save(request):
    if request.method == "POST":
        try:
            username = request.POST["username"]
            name = request.POST["name"]
            lastname = request.POST["lastname"]
            email = request.POST["email"]
            age = request.POST["age"]
            password = request.POST["password"]
            language = request.POST["language"]
            framework = request.POST["framework"]
            experience = request.POST["experience"]
            user = User.objects.create_user(username=username, email=email, password=password)
            user.first_name = name
            user.last_name = lastname
            user.save()
            programmer = Programmer(user=user, age=age, language=language, framework=framework, experience=experience)
            programmer.save()
        except:
            return redirect("/")
        else:
            return redirect("/")


# add project
def add_project_page(request, programmer_id):
    return render(request, "polls/add_project_page.html", {"programmer_id": programmer_id})


def add_project(request, programmer_id):
    if request.method == "POST":
        name = request.POST["name"]
        description = request.POST["description"]
        new_project = Project(
            programmer=Programmer.objects.get(pk=programmer_id),
            name=name,
            description=description,
        )
        new_project.save()
        programmers = Programmer.objects.order_by("-age")
        contex = {"programmers": programmers, "success": "new Project successfully created"}
    return render(request, "polls/index.html", contex)

portfolio/polls/templates/polls/add_project_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add project</title>
</head>
<body>
<form method="post" action="{% url 'polls:add_project' programmer_id %}">
        {% csrf_token %}
        <input type="text" name="name">
        <input type="text" name="description">
        <input type="submit" value="Add new project">
    </form>
</body>
</html>

portfolio/polls/templates/polls/add_user.html
<script>
    function validatePassword() {
        const password = document.getElementById("password").value;
        const length = password.length;
        const symbols = /[!@#$%^&*()_={}\[\]:;<>,.?~\\-]/;

        if (length < 8) {
            alert("Password must be at least 8 characters long.");
        } else if (!symbols.test(password)) {
            alert("Password must contain at least one special symbol (!@#$%^&*()_={}\[\]:;<s>,.?~\\-).");
        } else {
            alert("Password is valid.");
        }
    }
</script>
<form action="{% url 'polls:user_save' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:-</label>
    <input type="text" id="username" name="username">
    <label for="email">Email:----></label>
    <input type="text" id="email" name="email"><br><br>
    <label for="name">Name:----></label>
    <input type="text" id="name" name="name">
    <label for="lastname">Lastname:</label>
    <input type="text" id="lastname" name="lastname"><br><br>
    <label for="age">Age:------></label>
    <input type="number" id="age" name="age"><br><br>
    <label for="language">Language:-</label>
    <input type="text" id="language" name="language">
    <label for="framework">Framework:</label>
    <input type="text" id="framework" name="framework">
    <label for="experience">Experience year:</label>
    <input type="number" id="experience" name="experience"><br><br>
    <label for="password">-----------Password:</label>
    <input type="password" id="password" name="password"><br><br>
    <label for="password2">Confirm Password:</label>
    <input type="password" id="password2" name="password2"><br>
    <input type="button" value="Check Password" onclick="validatePassword()">
    <input type="submit" value="Submit">
</form>

portfolio/polls/templates/polls/detail.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About programmer</title>
    Name:{{programmer}}-->Surname:{{last_name}}-->age:{{age}}<br><br>
    {% for project in des %}
        -----------------------------<br>
        PROJ NAME: {{ project.name }}<br>
        PROJ DESC> {{ project.description }}<br>
        -----------------------------<br>
    {% endfor %}
    <a href="{% url 'polls:add_project_page' prog_id %}">Add project</a>
</head>
<body>
</body>
</html>

portfolio/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Programmers</title>
</head>
<body>
{% if success %}
    {{ success }}
{% endif %}
{% if programmers %}
    <ul>
    {% for person in programmers %}
        <li><a href="{% url 'polls:detail' person.id %}">{{ person.user.first_name }}___{{person.user.last_name}}</a></li>
    {% endfor %}
    </ul>
    <a href="{% url 'polls:add_user' %}">ADD USER</a>
{% else %}
    <p>No available.</p>
{% endif %}

</body>
</html>